### ISSUE TITLE
[Improvement] Own folder for DSCResource classes

### ISSUE THREAD

**Issue by rockaut** [vmware/dscr-for-vmware#1]
Wouldn't it be better to separate the DSCResource classes like `VMHostNtpSettings` in their own folder and files? Something like `Resources\VMHostNtpSettings.ps1` instead of directly in .psm1.

**Comment by dmilov** [comment]
Unfortunately this doesn't work. It's not possible to export DSC resource from dot sourced files. There is a workaround though we decided not to use it. It is to write the resources in separate files and then merge them in a single psm1 file with a script.

**Comment by lucdekens** [comment]
An indirect consequence of having one "big" file and Visual Studio Code [issue#869](https://github.com/PowerShell/vscode-powershell/issues/869) is that the infamous "Formatting PowerShell Document" pops up quite regularly.
The bigger the .psm1 is going to become, the more impractical it is going to be to work with Visual Studio Code.

**Comment by rockaut** [comment]
Also i think the more and more DSC Resources willl get implemented it will be very cumbersome to maintain PRs as each one has to merge the same files?

**Comment by SimeonGerginov** [comment]
We have started to work on the separation of the resources in different files.

**Comment by SimeonGerginov** [comment]
Resources are now separated in different files in the dev branch and there is a build script updating the psm1 and psd1 files.
