### ISSUE TITLE
Handling default values for resource properties

### ISSUE THREAD

**Issue by lucdekens** [vmware/dscr-for-vmware#101]
vSphere uses defaults for most of the optional properties.
How do we assign these defaults in a DSC resource?

Some options:
- make each DSC property required
- on the DSCProperty itself when it is not required
- in the Test and Set methods
- in a kind of Init method on each resource
- via an external (JSON ?) file (different files when different API/vSphere versions change the defaults)

Each of these has pros and cons, but I feel we should define how it shall be done, before more resources are introduced.

Somewhat related, how do we handle property dependencies?
When property A, for example has value 1, property B can only have values 1 and 2 but not 3.
Do we bury that in the code, or do we use a kind of definition language to document such restrictions?

**Comment by SimeonGerginov** [comment]
Well for now the method used in most resources is to define the default value on the property itself like:

```
 [DscProperty()]
 [DefaultVIServerMode] $DefaultVIServerMode = [DefaultVIServerMode]::Unset
```

However with different API/vSphere versions the external JSON File could be a better solution. We will think about it.

Could you give me a specific example of the property dependencies you have mentioned ?

**Comment by lucdekens** [comment]
I do see potential problems with assigning defaults for properties that are not Required.

An example of a dependency could be the maximum datastore capacity.
Depending on the VMFS version and the blocksize, the maximum capacity is different.

Perhaps not directly a default value, but a maximum we should know in our code to validate the provided number.

I was also considering, with the JSON file option, that an organisation could adapt/define it's default settings.

In that case there could be more property dependencies.

For example, when an organisation prefers to have their VSS by default use Beacon Checking to discover link failures, the default for the BeaconInterval in the Bridge resource should be different from zero.

**Comment by SimeonGerginov** [comment]
Yes the JSON file option looks like it will cover more cases than assigning defaults. We will discuss it more.

**Comment by lucdekens** [comment]
Consolidated in #203
