### ISSUE TITLE
Testing resource dependencies

### ISSUE THREAD

**Issue by lucdekens** [vmware/dscr-for-vmware#102]
We will have resources that are inter-related and use **DependsOn** lines.

Where shall we test these inter-dependencies?
In the Integration test for the base resource? Or as a separate Integration test?
Via a configuration file, containing all the resources?

**Comment by SimeonGerginov** [comment]
Well I think a separate Integration Test will be a good solution. Like the example test mentioned in the [CODING GUIDELINES](https://github.com/vmware/dscr-for-vmware/blob/master/CODING_GUIDELINES.md):

```
 It 'Should depend on resource <resource name>' {
     # Make sure that the current resource is depending on the right resource.
     $currentResource = Get-DscConfiguration | Where-Object { $_.Name -eq '<current resource name>' }

     $currentResource.DependsOn | Should -Be '<resource name>'
 }
```

**Comment by SimeonGerginov** [comment]
Following on my previous post, good examples on tests with `DependsOn`  can be found [here](https://github.com/vmware/dscr-for-vmware/blob/master/Source/VMware.vSphereDSC/Tests/Integration/Cluster/HACluster.Integration.Tests.ps1) and also [here](https://github.com/vmware/dscr-for-vmware/blob/master/Source/VMware.vSphereDSC/Tests/Integration/Datacenter.Integration.Tests.ps1). 

Does this answer your question ?

**Comment by lucdekens** [comment]
Ok, question is answered.
