### ISSUE TITLE
Composite resources, or not?

### ISSUE THREAD

**Issue by lucdekens** [vmware/dscr-for-vmware#103]
When a vSphere object is managed through multiple DSC resources, do we provide a Composite resource?
Or do we leave that to the user?

One such composite resource could be the Virtual Switch (VSS).
Instead of letting the user create a configuration file with all VSS related resources, we could offer a composite resource.

This would also allow us to tackle #102 by providing an Integration test for the composite resource.

**Comment by Outek** [comment]
It would be nice, if you can produce composite resources. We are using the Datum Module to generate all of our Dsc configurations. It would be an easy task to implement those composite resources with datum.

**Comment by lucdekens** [comment]
Fully agree, using Datum could be a next step.

**Comment by SimeonGerginov** [comment]
As mentioned in issue #104 we will think about adding different variations of the existing resources. The VSS is a good example because as we have the separate resources we can easily combine them in a new composite resource.

**Comment by SimeonGerginov** [comment]
The documentation was updated with section about Composite Resources via PR #119. Closing the issue.
