### ISSUE TITLE
Guideline: variations of a resource in separate resources or not?

### ISSUE THREAD

**Issue by lucdekens** [vmware/dscr-for-vmware#104]
There are many vSphere objects that can be present in **different variations**.
Shall we create each variation as a separate resource, or combine them in one resource?

Some examples:
1) **Virtual Switch Bridge**
There are 3 types of bridging: Auto, Bond and Simple, each with exclusive properties
One VMHostVssBridge resource or 3 different resources VMHostVssAutoBridge, VMHostVssBondBridge and VMHostVssSimpleBridge?

2) **Cluster**
A basic cluster resource with the Name property and separate resources/resource branches for HA, DRS and EVC, or all in 1 Cluster resource?

When a decision is taken, can this be included in the **Coding Guidelines**?

**Comment by SimeonGerginov** [comment]
Yes, we will discuss this more thoroughly and when we decide which approach to take, we will add a section to the [Coding Guidelines](https://github.com/vmware/dscr-for-vmware/blob/master/CODING_GUIDELINES.md).

**Comment by SimeonGerginov** [comment]
The documentation was updated with section about Composite Resources and whether or not to have separate Resources or just one via PR #119. Closing the issue.
