### ISSUE TITLE
Create base resource for inventory objects InventoryBaseDSC and extend it to resolve the path to a specific Inventory Item

### ISSUE THREAD

**Issue by dmilov** [vmware/dscr-for-vmware#11]
Create base resource for inventory objects. It should provide key properties to uniquely identify inventory objects.

**Comment by lucdekens** [comment]
Any progress on this one?
This would allow to tackle resources like Datacenter, Folder, Datastore, VDS, VM....

**Comment by SimeonGerginov** [comment]
I have mentioned the progress in #53.

**Comment by SimeonGerginov** [comment]
Added InventoryBaseDSC class via PR #80. Closing the issue.

**Comment by SimeonGerginov** [comment]
The InventoryBaseDSC class will be extended to resolve the path to a specific Inventory Item via PR #90.

**Comment by SimeonGerginov** [comment]
The InventoryBaseDSC class was extended with the path resolving via PR #90. Closing the issue.
