### ISSUE TITLE
Datastore in test helpers

### ISSUE THREAD

**Issue by davidwallis3101** [vmware/dscr-for-vmware#111]
are there any plans to add the datastore objects into the test helpers so that I can mock datastores.

Not using the test helpers specifically for the DSC resources I must add :)

If it was clear how the types are being determined I would submit a PR but even looking at the DLLs with ILSPY im not 100% how these have been created :)

**Comment by SimeonGerginov** [comment]
I think this is part of this issue #76 so the plan is to generate the whole content soon.

**Comment by SimeonGerginov** [comment]
As this is part of issue #76 you can check the progress there. Closing this issue.
