### ISSUE TITLE
[Improvement] Add instructions to keep a fork up to date

### ISSUE THREAD

**Issue by lucdekens** [vmware/dscr-for-vmware#116]
The Committing Guidelines document is very useful.

But since most contributors are probably not the **git gurus**, it could be useful to provide some example instruction on how to **keep one's fork up to date**.

This should not only include the **master** fork, but also instructions on how to get the local **branches** updated.

I just used

```
git remote add upstream https://github.com/vmware/dscr-for-vmware.git
git fetch upstream
git checkout master
git rebase upstream/master
git checkout <a-local-branch>
git rebase master
```

which seems to work for me (but I could be wrong).

Important to note, all changes on the **a-local-branch** need to be staged, before doing the rebase for your local branch.

**Comment by SimeonGerginov** [comment]
I agree, we will add this section to the Committing Guidelines document.

**Comment by SimeonGerginov** [comment]
Instructions were added to the Documentation via PR #119. Closing the issue.
