### ISSUE TITLE
[Feature] Implement DSC Resource for vSphere Firewall

### ISSUE THREAD

**Issue by Outek** [vmware/dscr-for-vmware#162]
DSC Resource that adds, updates or removes a vSphere Firewall Rule.
Servicename, TCP Ports, UPD Ports, Allowed IP Addresses

**Comment by SimeonGerginov** [comment]
Can you clarify something for me - you want the resource to modify the following file:

```
/etc/vmware/firewall/service.xml
```

by adding, updating and removing firewall rules?

**Comment by Outek** [comment]
Yes, that is correct.

**Comment by SimeonGerginov** [comment]
Similarly to issue #161 I think there is no public API available that covers the proposed operations on Firewall Rules. The only way I can think of is to edit the **services.xml** file through SSH but I have my reservations about this approach. What is your opinion on that ?

**Comment by Outek** [comment]
Well, i think it would be nice, if there is an api for this. Edit the xml should be the last try to reach this goal.

**Comment by Outek** [comment]
It's no longer possible to add custom rules.
