### ISSUE TITLE
Who maintains the Wiki pages?

### ISSUE THREAD

**Issue by lucdekens** [vmware/dscr-for-vmware#19]
Currently the Wiki pages on this repo are not open sourced.
Is it the intention to open up these pages to the community?

**Comment by SimeonGerginov** [comment]
Got it. Something we have to think about.

**Comment by lucdekens** [comment]
Related to this, can we have a Documentation folder with documentation for each DSC Resource that is added or modified?
From those MarkUp files you could generate the Documentation section on the Wiki page.

**Comment by SimeonGerginov** [comment]
Yes, this sounds like a good idea and we will think about it.

**Comment by SimeonGerginov** [comment]
We have added Documentation folder in the repository master branch containing the DSC Resources usages and examples from the repository wiki. Closing the issue.
