### ISSUE TITLE
Bug: Not able to ignore SSL/TLS Certificate Warning from VMware.vSphereDSC

### ISSUE THREAD

**Issue by jatinpurohit92** [vmware/dscr-for-vmware#196]
I am trying to write Configuration for my lab esxi hosts. During the compilation, it fails with below error, 

![CertErrorDSC](https://user-images.githubusercontent.com/55919052/65817410-217c3900-e224-11e9-8474-60c13cbe5b2f.PNG)

I have set my powercli configuration to Ignore Certificate warning and this works very well when i use Connect-VIServer cmdlet. Thanks.

**Comment by SimeonGerginov** [comment]
Hi @jatinpurohit92,
Could you please let me know what's your:

1. ``$PSversionTable.PSVersion``
2. ``Get-Module -Name VMware.PowerCLI -ListAvailable``
3. ``Get-PowerCLIConfiguration``
4. ``Get-Module -Name VMware.vSphereDSC -ListAvailable``

**Comment by jatinpurohit92** [comment]
@SimeonGerginov 
[PowerShell_transcript.LAPTOP-ERK9I8FS.KdU0qfVN.20191001101019.txt](https://github.com/vmware/dscr-for-vmware/files/3674434/PowerShell_transcript.LAPTOP-ERK9I8FS.KdU0qfVN.20191001101019.txt)
please find the attached transcript containing the requested information. Thanks

**Comment by SimeonGerginov** [comment]
Could you also provide the script that you are executing and the Configuration you are trying to apply. One problem could be that the **InvalidCertificateAction** is not set to **Ignore**. You can try to use [this](https://github.com/vmware/dscr-for-vmware/wiki/PowerCLISettings) Resource in your Configuration to Ensure PowerCLI is configured correctly before applying the other Resources.

**Comment by jatinpurohit92** [comment]
![image](https://user-images.githubusercontent.com/55919052/66037735-ecc2f700-e52d-11e9-8d35-1e9a96a91dc9.png)
1. Get-PowerCLISetting shows -_invalidservercertificate_ is set to Ignore.
2. I tried this with PowerCLISettings DSC resource but that failed to execute. 
![image](https://user-images.githubusercontent.com/55919052/66037880-3d3a5480-e52e-11e9-814c-7e8ae25531e4.png)

3. here is the configuration script which I am using.

[VMhostDemo2txtFile.txt](https://github.com/vmware/dscr-for-vmware/files/3680674/VMhostDemo2txtFile.txt)

**Comment by SimeonGerginov** [comment]
The problem occurs because the LCM runs with Windows System account, so the settings will be stored for the user that runs LCM PowerShell. Based on your settings for **AllUsers**, **InvalidCertificateAction** is not set to **Ignore**. There are two ways to achieve that:

1. You can use the [PowerCLISettings Resource](https://github.com/vmware/dscr-for-vmware/wiki/PowerCLISettings).
2. ```Set-PowerCLIConfiguration -Scope AllUsers -InvalidCertificateAction Ignore```

**Comment by jatinpurohit92** [comment]
@SimeonGerginov Thanks and appreciate all your help. I wasn't aware of LCM works with system account. Its resolved now after making about changes to the system.
