### ISSUE TITLE
Copyright

### ISSUE THREAD

**Issue by lucdekens** [vmware/dscr-for-vmware#197]
I suggest to collect a statement from each contributor in the style of "_I hereby assign copyright in this code to the project, to be licensed under the same terms as the rest of the code._"

The current code already seems to indicate that VMware has the copyright, but without any formal approval from the code authors, I doubt if that will hold its ground in court.

The advantages of signing off the copyright to a single entity (VMware in this case), are imho
- defending the copyright (if needed) by a single entity
- protect single contributors against liability
- avoid 'Chef' surprises

Discussion is welcome, and perhaps some feedback from a Legal Department somewhere could help.

**Comment by jakerobinson** [comment]
I am checking with legal on this.

**Comment by dirkhh-vmware** [comment]
Hi @lucdekens - no, VMware quite intentionally does NOT want a copyright assignment.
Submissions to open source projects on GitHub are broadly assumed to be under the same license as the code in the project, unless explicitly stated otherwise. The contributions to projects like this are copyright by the individual authors (or there employers, as applicable), but the overall work is then _licensed_ under the BSD-2 license.

**Comment by lucdekens** [comment]
@dirkhh-vmware - Thanks for clarifying that.

One more question (I'm a legalese noob I'm afraid), does the project, as a consequence, rely on the '[inbound=outbound](https://help.github.com/en/articles/github-terms-of-service#6-contributions-under-repository-license)' rule from GitHub?
And thus needs to stay on GitHub, unless the licensing is changed, or the new host has a similar implicit rule in place?

**Comment by dirkhh-vmware** [comment]
Not really - this is a rule that is widely accepted across open source projects and long predates the use of services like GitHub.
Many projects use a DCO (https://en.wikipedia.org/wiki/Developer_Certificate_of_Origin) to make this more obvious, but even without that unless a contributor explicitly states a different license (or additional licenses), it is generally accepted that the contribution is under the license under which the developer received the code they are contributing to.

**Comment by lucdekens** [comment]
Ok, thanks for the replies.

I suggest we close this issue.
