### ISSUE TITLE
[Improvement] Installing the module, missing configuration files

### ISSUE THREAD

**Issue by rockaut** [vmware/dscr-for-vmware#2]
Currently it isn't clearly documented how to install the module. Also you currently you need to clone the github repo to somewhere as the resource configurations files aren't included in the module folder.

You can read it between the lines and screenshots in the https://blogs.vmware.com/PowerCLI/2018/12/getting-started-dsc-for-vmware.html blogpost.

**Comment by dmilov** [comment]
We decided to have release zip without example configurations. They are available in the repo if somebody wants to use them as a reference. We'll consider adding help about in the module.

**Comment by jakerobinson** [comment]
@dmilov How close are we with putting this on the Gallery?

**Comment by dmilov** [comment]
> 
> 
> @dmilov How close are we with putting this on the Gallery?

Once we finish the in progress Cluster configuration resources we can create new release and publish it to the gallery.

**Comment by jakerobinson** [comment]
This can be closed since it's now on the gallery! :)
