### ISSUE TITLE
[Feature] Implement DSC resource to create, manage and delete datastore clusters

### ISSUE THREAD

**Issue by danielboth** [vmware/dscr-for-vmware#265]
A resource for managing datastore clusters seems absent at this moment, using VMware.vSphereDsc version 2.1.0.58.

**Comment by SimeonGerginov** [comment]
Thanks for the feature request. We will start working on the new DSC Resource for Datastore Clusters.

**Comment by SimeonGerginov** [comment]
**DatastoreCluster** DSC Resource was implemented via PR #267. For more information on how to use the **DatastoreCluster** DSC Resource see the [DatastoreCluster wiki](https://github.com/vmware/dscr-for-vmware/wiki/DatastoreCluster).
