### ISSUE TITLE
[Feature] Implement DSC Resource to manage DRS Rules

### ISSUE THREAD

**Issue by danielboth** [vmware/dscr-for-vmware#266]
One of the more tricky pieces of configuration to keep track of are DRS rules, for example VM anti-affinity when the VMs share a role so they should not be on the same hosts in a cluster. Currently there is no proper way to manage those with DSC. I would love to see a DSC resource that implements maintaining the DRS rules on the vSphere clusters.

**Comment by SimeonGerginov** [comment]
Thanks for the feature request. We will start working on the new DSC Resource for DRS rules.

**Comment by SimeonGerginov** [comment]
**DRSRule** DSC Resource was added via PR #269. For more information on how to use the new DSC Resource, please visit [DRSRule DSC Resource wiki](https://github.com/vmware/dscr-for-vmware/wiki/DRSRule).
