### ISSUE TITLE
[Feature] Implement DSC Resource that updates/removes a VMKernel Network Adapter, connected to a Distributed Port Group

### ISSUE THREAD

**Issue by vniks** [vmware/dscr-for-vmware#272]
This would help us to do changes for existing Host VMKernel adapters and for new host VMkernel adapter configuration on a distributed switch.

**Comment by SimeonGerginov** [comment]
Thanks for the feature request. We will start working on the new DSC Resource for a VMKernel Network Adapter, connected to a Distributed Port Group.

**Comment by SimeonGerginov** [comment]
**VMHostVdsNic** DSC Resource was added via PR #273. For more information on how to use the new DSC Resource, please visit [VMHostVdsNic DSC Resource wiki](https://github.com/vmware/dscr-for-vmware/wiki/VMHostVdsNic).

**Comment by vniks** [comment]
Thanks alot , this is working as expected
