### ISSUE TITLE
Add .vscode to .gitignore

### ISSUE THREAD

**Issue by SDBrett** [vmware/dscr-for-vmware#28]
This commit added .vscode into the project directory to provide a settings.json file. While I understand the reason would be to help ensure consistency with linting, the .vscode directory is typically considered to be locally specific.

I can see issues with getting PRs which include changes to .vscode requiring changes etc and overall increasing overhead. 

VSCode settings are already included in the formatting guidelines document.

**Comment by SimeonGerginov** [comment]
Yes, we think this is a good solution. I will merge the pull request.

**Comment by lucdekens** [comment]
I'm afraid I don't agree with this decision.
For consistency of formatting, I would prefer this directory to be part of the project.

Talking about issues, most of the comments I got on my PR are about formatting.
The settings.json file avoids this problem.

Even the PowerShell/PowerShell repo has a .vscode directory.
