### ISSUE TITLE
[Feature] Update DSC Resource VDPortgroup to allow vlan id to be specified

### ISSUE THREAD

**Issue by mikedonleyuoy** [vmware/dscr-for-vmware#289]
The standard switch resource (VMHostVssPortGroup) allows a vlanid to be specified, however, the VDPortgroup resource doesn't.  This limits the resources use.

**Comment by SimeonGerginov** [comment]
**VDPortGroup** DSC Resource was extended with **VLanId** property with PR #300. For more information and examples, check the documentation of the **VDPortGroup** DSC Resource [here](https://github.com/vmware/dscr-for-vmware/wiki/VDPortGroup).
