### ISSUE TITLE
VMware.PSDesiredStateConfiguration not published to powershell gallery.

### ISSUE THREAD

**Issue by Alta2048** [vmware/dscr-for-vmware#291]
Hi All,

Is there any chance that the module "VMware.PSDesiredStateConfiguration' will be published via the PSgallery?

PowerShell Gallery | Packages matching VMware.PSDesiredStateConfiguration : is not showing any result

`find-module 'VMware.PSDesiredStateConfiguration'`
 
do not reply

 `find-module 'vmware.vspheredsc'`

is working correctly

Workaround : clone the repository and run :

`Import-module -path YourPath\Source\VMware.PSDesiredStateConfiguration\VMware.PSDesiredStateConfiguration.psd1`

**Comment by KristiyanGK** [comment]
Hi, we are still currently working on new features for this module and that is why we haven't released it in the PowerShell Gallery. When the new features are complete we will have a new release here on the github page and on the Gallery.

**Comment by Alta2048** [comment]
Hi, Thanks for the information. Will wait for the release then.
