### ISSUE TITLE
[Feature] Add Host Services as resource

### ISSUE THREAD

**Issue by rockaut** [vmware/dscr-for-vmware#3]
I would like to contribute a Host Services resource to control those. Should be pretty easy i think as it's currently already included in PowerCLI. I just have to get in how DSCResources are implemented.

**Comment by dmilov** [comment]
Cool. You should start with https://github.com/vmware/dscr-for-vmware/blob/master/CONTRIBUTING.md 
We still don't have travis integrated to run the unit tests but expect to have it soon on the dev branch

**Comment by lucdekens** [comment]
Just submitted https://github.com/vmware/dscr-for-vmware/pull/35

**Comment by SimeonGerginov** [comment]
Closing the issue as #49 was merged.
