### ISSUE TITLE
error running start-vmwdscconfiguration

### ISSUE THREAD

**Issue by harrezzebra** [vmware/dscr-for-vmware#325]
I'm using visual studio code and powershell version 7.1.3, getting below error

VERBOSE: Invoking DSC Resource with id: [Datacenter]ENG_ACTON
Exception: C:\Windows\System32\WindowsPowerShell\v1.0\Modules\VMware.PSDesiredStateConfiguration\1.0.0.16\Classes\Public\DscConfigurationRunner.ps1:203:13
Line |
 203 |              throw $dscResourceErrorMessage
     |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Set method of Datacenter DSC Resource failed with the following
     | error: The term 'Invoke-DscResource' is not recognized as a name of a
     | cmdlet, function, script file, or executable program. Check the
     | spelling of the name, or if a path was included, verify that the path
     | is correct and try again.

**Comment by jatinpurohit92** [comment]
https://github.com/vmware/dscr-for-vmware/blob/master/VMware.PSDesiredStateConfiguration.md Please check this out. 

Have you enabled the experimental feature?

**Comment by harrezzebra** [comment]
working after enabling experimental feature. thanks
