### ISSUE TITLE
Define target Code Coverage percentage for Pester Unit tests

### ISSUE THREAD

**Issue by lucdekens** [vmware/dscr-for-vmware#34]
Since you are looking at a build pipeline, what would be the targeted code coverage percent for the Pester Unit tests?
Currently there are no clear directives on what Pester Unit tests should cover. 
With a potential risk of phantom, or even worse malicious, code in the contributions from the community.

Btw, Pester code coverage for DSC resource classes is an open issue.
See the Pester [issue#731](https://github.com/pester/Pester/issues/731)

**Comment by SimeonGerginov** [comment]
We will work on this issue and include it in the build pipeline with Travis CI.

**Comment by SimeonGerginov** [comment]
As of right now the Code Coverage of the project is 94 percent, so I think 90 percent will be a good starting number for the coverage of the DSC Resources. We will soon update the documentation with section specific to Code Coverage on pull requests.

**Comment by SimeonGerginov** [comment]
Target Code Coverage has been added to the repository master branch. Closing this issue.
