### ISSUE TITLE
Can we flatten the Describe block layout for Pester Unit tests?

### ISSUE THREAD

**Issue by lucdekens** [vmware/dscr-for-vmware#36]
In the Coding Guidelines it is proposed to have the following layout
 ```powershell
  Describe 'MyResource' {
      Describe 'MyResource\Set' {
          ...
      }

      Describe 'MyResource\Test' {
          ...   
      }

      Describe 'MyResource\Get' {
          ...
      }
  }
 ```
But since Pester currently only checks **Tag**s (see issue [#770](https://github.com/pester/Pester/issues/770)) on the **top level Describe**, we always have to run the complete test file. Which can be annoying when developing the tests.
PS: the **TestName** parameter does the same

Would the following be an acceptable layout?

Since the MyResource is already present in the nested Describe blocks, I don't think we would miss anything.
 ```powershell
    Describe 'MyResource\Set' -Tag 'Set' {
          ...
    }

    Describe 'MyResource\Test' -Tag 'Test' {
          ...   
    }

    Describe 'MyResource\Get' -Tag 'Get' {
          ...
    }
  }
 ```
And this will allow us to run a specific Describe block with
```
Invoke-Pester .\Unit\MyResource.Unit.Tests.ps1 -Tag 'Set'
```

**Comment by SimeonGerginov** [comment]
Looks good! I also think it looks cleaner that way.

**Comment by SimeonGerginov** [comment]
Removed the wrapper Describe block and added Tags for all Unit Tests with PR #64. Closing the issue.
