### ISSUE TITLE
[Feature] Add Host Power policy

### ISSUE THREAD

**Issue by rockaut** [vmware/dscr-for-vmware#4]
I would like to contribute the host power policy setting.

**Comment by SimeonGerginov** [comment]
Cool. If you have any questions regarding the implementation, do not hesitate to ask !

**Comment by rockaut** [comment]
Have the working code already but writing tests is .... hard ... haven't ever written tests in powershell.

**Comment by SimeonGerginov** [comment]
Yes, it is better if each resource has unit tests covering the functionality. If you have questions about implementing the tests feel free to ask !

**Comment by rockaut** [comment]
Redone PR but still Unit-Tests missing because of issue #16 .
Any hint how to solve this.

**Comment by SimeonGerginov** [comment]
View issue [#16.](https://github.com/vmware/dscr-for-vmware/issues/16)

**Comment by SimeonGerginov** [comment]
@rockaut what is the status of the Resource ?

**Comment by SimeonGerginov** [comment]
The Resource implementation will continue in issue #150. Closing the issue.
