### ISSUE TITLE
Enums in Integration tests

### ISSUE THREAD

**Issue by lucdekens** [vmware/dscr-for-vmware#43]
How shall we integrate enums in the Integration tests?
In the current setup/layout, the enums created for the DSC resources, are not known in the integration test environment.
As an example, the VMHostService resource uses the [ServicePolicy] enum.
How can we use these enum values in the integration tests?

**Comment by SimeonGerginov** [comment]
If I understand it correctly you want to have:

```
$servicePolicy = [ServicePolicy]::Automatic
```
Instead of:

```
$servicePolicy = "Automatic"
```

**Comment by lucdekens** [comment]
Exactly.
That would avoid invalid valid, typos...

**Comment by lucdekens** [comment]
That sounds like the best solution.
Do you intend to provide an integration test template, besides the instructions in the Coding Guidelines?

**Comment by SimeonGerginov** [comment]
Templates for both Unit and Integration Tests sound like a good idea. We will discuss it!
