### ISSUE TITLE
Update all documentation and build procedures to work with master branch 

### ISSUE THREAD

**Issue by SimeonGerginov** [vmware/dscr-for-vmware#44]
We currently plan to move all content from the dev branch to the master branch and then continue only with the master branch as contributions will be made via pull request. So update of the documentation and build procedures to work with master branch is needed.

**Comment by SimeonGerginov** [comment]
Message for current contributors to the repository with pull request (@lucdekens, @SDBrett, @rockaut) : Next week we will have update on the repository structure: Master branch will contain all new code and documentation. After that we plan to remove the dev branch, so be ready to sync the branches you are working on with the master branch to avoid conflicts in the files.

**Comment by SimeonGerginov** [comment]
(@lucdekens, @SDBrett, @rockaut) : We have just updated the repository: Now the master branch contains the latest changes and we have updated the documentation for Contributing. So right now the plan is to remove the dev branch next week, so you have time to sync your branches with the new changes.

**Comment by lucdekens** [comment]
For my understanding:

- we back up our local repo (should it contain changes that have not been pushed yet)
- we re-establish a fork from the master on vmware/dscr-for-vmware
- on our fork we create a dev branch, against which we will do our changes
- against which branch do we create a PR next week? A new dev branch on vmware/dscr-for-vmware, that you will create next week?

**Comment by SimeonGerginov** [comment]
By bullet points:

1. Yes back up your local repository, so that you do not lose the changes you made.
2. Yes update the fork to have the latest changes added to master(code, build and docs).
3. Yes on your fork create branch where you do your changes.
4. Against the master branch as of next week. We do not plan to add new branches because the current situation was that the dev and master branches had different documentations, which resulted in confusion. So when a new feature is ready to be added (after a pr was opened, the Travis build passed, the pr was approved via review) then the pr will be merged and the master branch will contain the new changes (Travis CI will take care to update the psm1 and psd1 files).

**Comment by lucdekens** [comment]
Sounds good!
I'll launch my VMHostService PR next week (after the dev branch is gone)

**Comment by SimeonGerginov** [comment]
Just deleted the **dev** branch. Now latest changes are in the **master** branch. Closing the issue.
