### ISSUE TITLE
Keep getting emails from VMware CLA Bot

### ISSUE THREAD

**Issue by lucdekens** [vmware/dscr-for-vmware#45]
Although my commits seem to contain

```
Signed-off-by: Luc Dekens <dekens.luc@gmail.com>
```

I keep getting an email from the VMware CLA Bot, telling me that
![clabot](https://user-images.githubusercontent.com/7760649/50684858-50f47100-1017-11e9-9116-998347f8c43f.jpg)

Am I missing something?

**Comment by SimeonGerginov** [comment]
Check if commit a5d8f98 is signed.

**Comment by lucdekens** [comment]
I didn't.
Now the obvious question, how do I sign off an old commit?

**Comment by SimeonGerginov** [comment]
I think this [Article](https://help.github.com/articles/changing-a-commit-message/) will be helpful to achieve it. Just look at the "Amending older or multiple commit messages" section of the article.

**Comment by SimeonGerginov** [comment]
Added the git template to the repository. Closing the issue.
