### ISSUE TITLE
[Feature] Add VMHostSyslog

### ISSUE THREAD

**Issue by SimeonGerginov** [vmware/dscr-for-vmware#52]
Resource implementation already started #51 by @lucdekens.

**Comment by lucdekens** [comment]
How do you intend to organise the request for and the coding of new resources?
I guess we want to avoid multiple people working on the same?
On the other hand, when a new resource is claimed what would be the eventual allowed time interval for the development? Or perhaps a status report once a week for a claimed resource?
We probably don't want to end up with blocked resources, where nothing is happening?

I know, a lot of questions, and probably not a popular topic, but I think there better be some kind of rules/arrangements, before the problem actually pops up :-)

Worth a separate issue?

**Comment by SimeonGerginov** [comment]
Yes I also think we need separate issue for this topic, so we will think about how to address it.

**Comment by lucdekens** [comment]
Just created #53
