### ISSUE TITLE
Define some basic rules

### ISSUE THREAD

**Issue by lucdekens** [vmware/dscr-for-vmware#53]
Since this is an open source project, many contributors can participate.
While this is a great principle, this would also require some basic guidelines/conventions.

Some questions such guidelines might address:

- Must each proposed new resource be announced via an Issue?
- Who will review these new, proposed resources?
- What will be the status/label of a new, proposed resource that is approved for development? Up for grabs?
- Will participants be allowed to volunteer for such a new, proposed resource?
- Is that a FIFO concept? Or will volunteers be reviewed and chosen by the owners of the repo?
- When such a new resource is assigned, how does the assignee report on progress? Interval? Format?
- Can the development of a new resource be assigned to multiple assignees?
- When an assignee doesn't provide feedback for a longer, well defined period, will the Issue be opened up for a new Assignee?

**Comment by lucdekens** [comment]
One point I forgot to mention, do you guys have a kind of roadmap in mind?

**Comment by dmilov** [comment]
https://github.com/vmware/dscr-for-vmware/blob/master/CONTRIBUTING.md this should be place with all the needed information for start contributing. The process is not strictly defined though, we'll update the doc accordingly.

**Comment by SimeonGerginov** [comment]
We have added new section to the CONTRIBUTING.md about "Proposing DSC Resources". Closing the issue.
