### ISSUE TITLE
Create Wiki page with tips & tricks

### ISSUE THREAD

**Issue by lucdekens** [vmware/dscr-for-vmware#55]
To avoid that every contributor to this repo makes the same mistakes and falls into the same pitfalls, it would be nice to have a kind of FAQ.
This FAQ should contain guidelines, but also workarounds for known issues.

**Comment by SimeonGerginov** [comment]
For the wiki page with tips and tricks do you have some initial questions you want to be answered there ?

**Comment by lucdekens** [comment]
In theory I would say all questions contributors might have, and that are not covered in the CONTRIBUTING.md file.
Mostly practical Q&A.
We already discussed quite a few in other issues and reviews.

My (personal) starting list
- Suggest some tools to use?
- How to follow/automate the formatting guidelines. For example, the placement of curly braces, and how to automate this in VSC (settings.json)
- Practical guidelines for working with git and this repo
  - how this repo is set up and who manages it (merge-wise)
  - the minimum required git commands
  - possible GUI alternatives
- How to write resources that require different levels of coding?
  - the ones where all functionality is covered by PowerCLI cmdlets
  - the ones where functionality that Get-View and ExtensionData
  - the ones where all with functionality that requires esxcli
- How to design Unit tests for each of these, especially the mocking
- What shall be covered in the Integration test? What am I testing in fact?
...

**Comment by SimeonGerginov** [comment]
We have added the [Tips & Tricks](https://github.com/vmware/dscr-for-vmware/wiki/Tips-&-Tricks) page to the Wiki. I will close this issue as the page is created but will create another where request can be made about adding more sections and content to the page.
