### ISSUE TITLE
Can we add the VMware.vSphereDSC module files to .gitignore?

### ISSUE THREAD

**Issue by lucdekens** [vmware/dscr-for-vmware#56]
Since we are not supposed to commit the 2 VMware.vSphereDSC module files (.psm1 & .psd1), can we add the 2 files to .gitignore?

**Comment by SimeonGerginov** [comment]
This may create confusion when Travis is committing to the repository, because it will ignore both files and the module will not be updated this way.

**Comment by lucdekens** [comment]
Ok, I didn't consider that.
