### ISSUE TITLE
[Feature] Add VSS resource

### ISSUE THREAD

**Issue by lucdekens** [vmware/dscr-for-vmware#58]
I would like to add a resource for a Standard Switch (VSS).

Until #11 is completed, the placement in a Network folder will be left out.

**Comment by SimeonGerginov** [comment]
At the moment only the Composite VSS Resource is missing. The other ones were already added to the repository and also [released](https://github.com/vmware/dscr-for-vmware/releases/tag/v2.0).

**Comment by SimeonGerginov** [comment]
StandardSwitch Composite DSC Resource was implemented via PR #251. Closing the issue.
