### ISSUE TITLE
Proposal to introduce hierarchy structure in DSCResources folder 

### ISSUE THREAD

**Issue by lucdekens** [vmware/dscr-for-vmware#59]
When we start to tackle more complex resources in a vSphere environment, there will be more and more separate resources that logically belong together.

This proposal suggests to organise these resources in separate subfolders under the **DSCResources** folder. These subfolders will help in visualising the relations between resources.

As an example, the standard Virtual Switch (VSS) would consist of the following separate, but related, resources:

- VMHostVSS
- VMHostVSSSecurity
- VMHostVSSShaping
- VMHostVSSTeaming
- VMHostVSSAutoBridge
- VMHostVSSBondBridge
- VMHostVSSSimpleBridge

Under this proposal the files for these resources could be organised something like this.
![folder](https://user-images.githubusercontent.com/7760649/50957417-76bdc200-14be-11e9-805d-63b7f2147740.png)

The build script only needs a minor change to support this afaik.

The same concept could eventually be adopted for other folders in the repository (Documentation, Configurations...)

**Comment by SimeonGerginov** [comment]
Yes, this looks like a wonderful solution. Go with it!

**Comment by SimeonGerginov** [comment]
The build was updated with PR #61. Closing the issue.
