### ISSUE TITLE
Please update README.md

### ISSUE THREAD

**Issue by lucdekens** [vmware/dscr-for-vmware#63]
Now that we are merging all PRs into the master, I assume that each merge should also update the README.md file?

Since it is the first info a visitor/user sees, it would be handy to list at least all the available DSC resources.

And a related question, is README.md intended for the git administrators, or can all users contribute?

**Comment by lucdekens** [comment]
That sounds like a good idea.

Question: can't you create (as part of the build pipeline) a ToC or table in the Wiki from the files under Documentation?

**Comment by SimeonGerginov** [comment]
Yes, we are also considering to generate the **wiki** from the content in the Documentation folder and not doing it every time a new Resource is added.

**Comment by SimeonGerginov** [comment]
We have added the wiki link to the README.md. We will think about a way to update the Wiki via the build pipeline. When we are ready with a solution, we will create separate issue! Closing the issue.
