### ISSUE TITLE
[Feature] Add DSC resource for cluster configuratons

### ISSUE THREAD

**Issue by BlueArcherX** [vmware/dscr-for-vmware#72]
We have a large environment (300+ clusters) and a large number of engineers that can make changes (30+) but who may not be fully aware of the requirements for every cluster.  We would like to do some enforcement of the settings on the cluster objects.  These  often get changed (whether inadvertently or on purpose but then not set back to the desired config).

1. HA state
2. Failure response settings
3. Admission Control settings
4. DRS state
5. DRS automation level
6. DRS thresholds
7. DRS dristribution, memory load balancing, and CPU over-commit settings
8. DRS and HA Advanced Settings

**Comment by dmilov** [comment]
Thank You for this feature request! We need such specific use-cases to prioritize the content of this project.  Cluster resource will be prioritized right after the base classes for inventory resources.

**Comment by SimeonGerginov** [comment]
@BlueArcherX Can you provide us with the keys for these Advanced Settings: 
```DRS dristribution, memory load balancing, and CPU over-commit``` settings. After some research I think they are ```'LimitVMsPerESXHostPercent', 'PercentIdleMBInMemDemand' and 'MaxVcpusPerClusterPct'```.

**Comment by BlueArcherX** [comment]
You nailed it, those are the ones I had in mind!

**Comment by SimeonGerginov** [comment]
@BlueArcherX, the Cluster Resources are ready:

1. You can use the [HACluster Resource](https://github.com/vmware/dscr-for-vmware/wiki/HACluster) to configure the HA Settings.
2. You can use the [DrsCluster Resource](https://github.com/vmware/dscr-for-vmware/wiki/DrsCluster) to configure the Drs Settings.
3. You can use the [Cluster Composite Resource](https://github.com/vmware/dscr-for-vmware/wiki/Cluster) to configure both HA and Drs Settings.

**Comment by SimeonGerginov** [comment]
@BlueArcherX we have renamed the InventoryPath property of the base class to DatacenterInventoryPath via PR #113. So if you have existing configurations with the Cluster Resources, you should rename it there.

**Comment by BlueArcherX** [comment]
Nice! Thank you! I will try to find some time in the next few weeks to develop against this.  I really appreciate it.

**Comment by SimeonGerginov** [comment]
Excellent! And thanks for the specific use case you have provided us with! Closing the issue.
