### ISSUE TITLE
Generate Add-Type content for TestHelpers

### ISSUE THREAD

**Issue by lucdekens** [vmware/dscr-for-vmware#76]
Isn't it possible to generate the C# code for the Add-Type in the TestHelpers module(s)?
I assume that the object definitions are available, and that a tool (swagger-like) should be able to generate that code?

**Comment by SimeonGerginov** [comment]
This is a good idea, we will research it if it is possible to generate it this way.

**Comment by SimeonGerginov** [comment]
We will start the generation of the C# code with the types from the 'VMware.Vim' assembly and continue with the other assemblies.

**Comment by lucdekens** [comment]
We should perhaps update the title of this Issue, since we are now using a .cs file instead of Add-Type?

**Comment by SimeonGerginov** [comment]
Well, we are still using Add-Type and passing the cs file/s to the Path property.

**Comment by SimeonGerginov** [comment]
The types were generated and added to the Repository via PR #118. The documentation was also updated (the section about defining types was removed) via PR #119. Closing the issue now.
