### ISSUE TITLE
How and where shall DependsOn be tested?

### ISSUE THREAD

**Issue by lucdekens** [vmware/dscr-for-vmware#78]
When we have resources depending on other resources being present:
- shall we do any tests for the DependsOn parameter?
- shall these tests go under Unit and/or Integration testing?

**Comment by SimeonGerginov** [comment]
Well DependsOn is specific for Configurations, so testing it in the Unit Tests would not be possible. As for the Integration Tests I think we can add the logic there. It will be a good addition. I will research it more thoroughly.

**Comment by SimeonGerginov** [comment]
We have added a section in the [Coding Guidelines](https://github.com/vmware/dscr-for-vmware/blob/master/CODING_GUIDELINES.md) describing how to test DependsOn parameter. Closing the issue.
