### ISSUE TITLE
Can we store the Add-Type data for the TestHelpers in a .cs file?

### ISSUE THREAD

**Issue by lucdekens** [vmware/dscr-for-vmware#79]
When we store the C# definitions in a separate .cs file, and use **Add-Type -Path**, we will have better control over the C# code (syntax, lint...).

**Comment by SimeonGerginov** [comment]
Yes with this, we can maintain better the TestHelper Module.

**Comment by SimeonGerginov** [comment]
The types were moved to a separate cs file via #87. Closing the issue.
