### ISSUE TITLE
Cannot connect to vCenter

### ISSUE THREAD

**Issue by SDBrett** [vmware/dscr-for-vmware#8]
When attempting to perform a Test-DSCConfiguration I am getting errors during the process of connecting to vCenter.

```
Cannot establish connection to server vcsa.sdbrett.lab.
    + CategoryInfo          : NotSpecified: (:) [], CimException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException
    + PSComputerName        : localhost
```

Connection with PowerCLI outside of DSC works ok.

Windows 10
PS version: 5.1
PowerCLI 11.0

VCSA 6.7U1

**Comment by dmilov** [comment]
First guess is PowerCLI Settings for your user are not the same as for AllUsers. DSC LCM runs PowerShell as a system user. In case InvalidCertificateAction for example is configured to Ignore for you user and this allows connection to the server. InvalidCertificateAction could be different for all users that to make connect to fail. 

Configure PowerCLI Settings for AllUsers on the machine where LCM runs

Set-PowerCLIConfiguration -Scope AllUsers


If that doesn't help we have to check the DSC logs for the error details

https://docs.microsoft.com/en-us/powershell/dsc/troubleshooting/troubleshooting

You cant try to get errors from the DSC logs following way

Get-WinEvent -LogName "Microsoft-Windows-Dsc/Operational" | Where-Object { $_.LevelDisplayName -eq "Error" }

**Comment by SimeonGerginov** [comment]
Improve error handling to display server error.

**Comment by SDBrett** [comment]
@SimeonGerginov if you're going to improve error handling, it would be helpful to properly kill the task if connect-viserver fails. 

Currently if it fails the process will still continue to attempt the next step such as get-vmhost

**Comment by SDBrett** [comment]
Confirming resolved with running `Set-PowerCLIConfiguration -Scope AllUsers -InvalidCertificateAction Ign
ore` from an administrator PoSH session
