### ISSUE TITLE
Use a Try-Finally construct as a standard for Pester tests

### ISSUE THREAD

**Issue by lucdekens** [vmware/dscr-for-vmware#84]
A common best practice for Pester tests seems to be to encapsulate Pester tests in a Try-Finally construct.
Since a Finally block is always run, this allows for a cleanup of the environment, independent of the Try block outcome.

As a reference, have a look at the Pester Unit and Integration [test templates](https://github.com/PowerShell/DscResources/tree/master/Tests.Template) that MSFT provides in their DSCResources repo.

The general layout:

```
function Invoke-TestSetup
{
    # Init code
}

function Invoke-TestCleanup
{
    # Cleanup code
}

Try
{
    Invoke-TestSetup
    # Tests
}
Finally
{
    Invoke-TestCleanup
}
```

**Comment by SimeonGerginov** [comment]
Yes, this would help in our case because we have defined the BeforeAllTests and AfterAllTests functions and with this we can call BeforeAllTests in the beginning of the try block and AfterAllTests in the Finally block.

**Comment by SimeonGerginov** [comment]
All Unit and Integration Tests have been refactored to use Try-Catch via PR #94. Closing the issue.
