### ISSUE TITLE
Consider adopting the MSFT guidelines for DSC resources

### ISSUE THREAD

**Issue by lucdekens** [vmware/dscr-for-vmware#85]
MSFT has published extensive guidelines for contributing to their [DSCResources repo](https://github.com/PowerShell/DscResources).

Instead of reinventing the wheel, consider adopting these guidelines, where applicable.

For example, the [DSC Resource Style Guidelines & Best Practices](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) document has a very extensive list of guidelines and best practices.

**Comment by SimeonGerginov** [comment]
Yes, we can update the [Tips and Tricks wiki page](https://github.com/vmware/dscr-for-vmware/wiki/Tips-&-Tricks) with more guidelines and best practices.

**Comment by SimeonGerginov** [comment]
We have added the guidelines via PR #97 in [Style Guidelines](https://github.com/vmware/dscr-for-vmware/blob/master/STYLE_GUIDELINES.md). Closing the issue.
