### ISSUE TITLE
How shall we handle initial PowerCLI configuration settings?

### ISSUE THREAD

**Issue by lucdekens** [vmware/dscr-for-vmware#9]
When applying configurations or when running Unit and Integration tests on fresh environments, we hit issues.
For example, PowerCLI by default is not configured to ignore invalid certificates.
Not as critical, but equally annoying, the CEIP prompt and the deprecated warnings are there by default.

How should the DSCR handle this?
By default set this options via Set-PowerCLIConfiguration?
Or make that a separate DSC resource?

**Comment by dmilov** [comment]
At the moment you can use AllUsers scope on the machine where LCM runs.

Set-PowerCLIConfiguration -Scope AllUsers

Special resource for configuring PowerCLI settings on LCM is needed for the purpose.

Duplicate of #10

**Comment by lucdekens** [comment]
Ok, close this one and continue with #10
