### ISSUE TITLE
Module versioning

### ISSUE THREAD

**Issue by lucdekens** [vmware/dscr-for-vmware#92]
The current pipeline doesn't change the module version.

I propose to align with [Powershell RFC0004](https://github.com/PowerShell/PowerShell-RFC/blob/master/1-Draft/RFC0004-PowerShell-Module-Versioning.md), which is [SemVer](https://semver.org/) based, and implement this in the build pipeline.

**Comment by SimeonGerginov** [comment]
Yes, we will add this feature to the build pipeline.

**Comment by SimeonGerginov** [comment]
The Module Versioning was added to the Build Pipeline via PR #110. Closing the issue.
