### ISSUE TITLE
Request to introduce a CHANGELOG document

### ISSUE THREAD

**Issue by lucdekens** [vmware/dscr-for-vmware#93]
While the repo is growing it might become difficult for contributors to discover what was added, removed or changed at what point in time.

To be able to easily see such changes, I propose to create a CHANGELOG document in the repo.

A PR should contain a standardised description of the changes, additions... it contains.
The build pipeline can insert that text into the CHANGELOG when the PR is merged.

The alternative is that the repo admins maintain the CHANGELOG document manually.

Or a mix of both.

**Comment by jakerobinson** [comment]
This happens at release or tag time. We currently only have one release at this point, but I believe we should make these on a more frequent basis. 

e.g. https://github.com/vmware/dscr-for-vmware/releases/tag/v1.0

**Comment by lucdekens** [comment]
Thanks for the feedback.
Btw, I think #92 is related, whose implementation would also make it a lot easier to report issues vs a specific version.

**Comment by SimeonGerginov** [comment]
The Module Versioning was added to the Build Pipeline via PR #110.

**Comment by lucdekens** [comment]
Thanks for that ( #92  ).

But doesn't that exactly prove my point.
Where can I find back what changed in which merge?

Jake's remark to relate this to release or tag time doesn't make sense imho.
A Changelog should be related to the merges, not to the version tagging (which someone can do after a number of merges as far as I'm concerned).

These seem to be corporate rules applied to an open (?) source project.

**Comment by SimeonGerginov** [comment]
A CHANGELOG.md could be added to the repository but a few things should be considered:

1.  Travis CI does not have an environment variable for PRs description at the moment: [Environment Variables](https://docs.travis-ci.com/user/environment-variables/). With that in mind the automation of the process does not seem to be straightforward.
2. The PRs description should go to review as well because the CHANGELOG document should follow some standards.

So the way I see it at the moment the only solution is to have the repository admins update the document after every merged pull request.

What are your thoughts ?

**Comment by lucdekens** [comment]
There are several plugins available afaik.
See for example [Git Changelog Lib](https://github.com/tomasbjerre/git-changelog-lib)

We could also consider 'semantic releases' (see my previous release comments), and adapt something like [The way to fully automated releases in open source projects](https://medium.com/@kevinkreuzer/the-way-to-fully-automated-releases-in-open-source-projects-44c015f38fd6)

**Comment by SimeonGerginov** [comment]
Ok I will take a look at the links you sent and we will continue the discussion.

**Comment by lucdekens** [comment]
The 2nd link also shows how could perhaps better organise and document commits.
And you could still keep the, what I call, 'corporate' release cycle.

**Comment by SimeonGerginov** [comment]
Another option I can think of now is to add the CHANGELOG document to the review process - Adding a new section to it with the changes in the PR. This way it will go through a review process and it will be up to the standard of the document. We can also add a template which shows how a change log should look like to avoid a confusion.

**Comment by lucdekens** [comment]
But will that not force us to enter the same info twice, in the commit and in the CHANGELOG?
Which is bound to go wrong at some point.

**Comment by SimeonGerginov** [comment]
Well in my opinion the two things will be slightly different. For example the commit message subject should be small and informative like: `Add VSS Resource`. The CHANGELOG file should contain a little more information that gives a brief description of the change. This is valid for the commit as well: The subject should be small and informative and the body should provide the adequate description. So in our case we can move the commit message body part to the CHANGELOG file and the commit message will only contain the subject without a body.

**Comment by lucdekens** [comment]
I'm afraid I don't agree.
Modern dev environments in fact have standardised commit messages, with a lot more info in there.
Have, for example, a look at the [Angular Commit Guidelines](https://github.com/angular/angular/blob/22b96b9/CONTRIBUTING.md#commit).

**Comment by SimeonGerginov** [comment]
Looks like the [GitHub API](https://developer.github.com/v3/pulls/#get-a-single-pull-request) can provide information about the Pull Requests. So this way we can automate the process.

**Comment by lucdekens** [comment]
Btw, in a similar way, if that requirement exists, we could add a RELEASELOG as well I guess?

**Comment by SimeonGerginov** [comment]
Well we certainly can think in that direction after we are ready with the CHANGELOG.md. For now the [Release page](https://github.com/vmware/dscr-for-vmware/releases) has all the needed information.

**Comment by SimeonGerginov** [comment]
Changelog document was introduced to the repository via PR #145. Also the update of the document is part of the build now. Closing the issue.
